#!/usr/bin/env bash
set -euo pipefail

# =========================
# 基础检查
# =========================
if ! grep -qiE 'debian|ubuntu' /etc/os-release; then
  echo "❌ 此脚本仅支持 Debian / Ubuntu 系"
  exit 1
fi

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "❌ 请使用 root 或 sudo 运行"
  exit 1
fi

RAM_MB=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)
CORES=$(nproc 2>/dev/null || echo 1)

DISK_SWAPS="$(swapon --noheadings --raw --output=NAME 2>/dev/null | grep -vE '^/dev/zram[0-9]+$' || true)"
HAS_DISK_SWAP=0
[[ -n "${DISK_SWAPS}" ]] && HAS_DISK_SWAP=1

# =========================
# 函数区
# =========================
backup_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  cp -a "$f" "${f}.bak.$(date +%Y%m%d%H%M%S)"
  echo "🧷 已备份: ${f}.bak.*"
}

# 找到根分区底层物理磁盘（尽量）
root_base_disk() {
  local src base pk
  src="$(findmnt -n -o SOURCE / 2>/dev/null || true)"
  [[ -n "$src" ]] || { echo ""; return 0; }

  # 例：/dev/sda2, /dev/nvme0n1p2, /dev/mapper/xxx, UUID=..., overlay...
  if [[ "$src" =~ ^/dev/ ]]; then
    base="$(lsblk -no PKNAME "$src" 2>/dev/null | head -n1 || true)"
    if [[ -n "$base" ]]; then
      echo "$base"
      return 0
    fi
    # 有些场景 PKNAME 为空，退化为 KNAME
    base="$(lsblk -no KNAME "$src" 2>/dev/null | head -n1 || true)"
    echo "$base"
    return 0
  fi

  # 处理 UUID=... 或其他：用 findmnt -> SOURCE 再喂给 lsblk 可能无效，直接返回空
  echo ""
}

disk_is_rotational() {
  local disk="$1"
  [[ -n "$disk" ]] || { echo "unknown"; return 0; }
  local p="/sys/block/${disk}/queue/rotational"
  [[ -f "$p" ]] || { echo "unknown"; return 0; }
  if [[ "$(cat "$p")" == "1" ]]; then
    echo "hdd"
  else
    echo "ssd"
  fi
}

# 选择 swapfile 放置的挂载点（/ /var /home）里可用空间最大的那个
best_swap_mountpoint() {
  local best_mp="/" best_free=-1
  local mp free
  for mp in / /var /home; do
    if mountpoint -q "$mp" 2>/dev/null || [[ "$mp" == "/" ]]; then
      free="$(df -BM "$mp" 2>/dev/null | awk 'NR==2{gsub(/M/,"",$4); print int($4)}' || echo 0)"
      if (( free > best_free )); then
        best_free=$free
        best_mp=$mp
      fi
    fi
  done
  echo "$best_mp"
}

root_free_mb() {
  df -BM / | awk 'NR==2{gsub(/M/,"",$4); print int($4)}'
}

update_fstab_swap_pri_all() {
  local pri="$1"
  local fstab="/etc/fstab"
  backup_file "$fstab"

  awk -v pri="$pri" '
    BEGIN{OFS="\t"}
    /^[[:space:]]*#/ {print; next}
    NF<4 {print; next}
    $3=="swap" {
      opts=$4
      if (opts ~ /(^|,)pri=[0-9]+(,|$)/) {
        gsub(/(^|,)pri=[0-9]+(,|$)/, "\\1pri=" pri "\\2", opts)
        gsub(/,,+/, ",", opts)
        sub(/^,/, "", opts); sub(/,$/, "", opts)
      } else {
        if (opts=="" || opts=="-") opts="sw"
        opts=opts ",pri=" pri
      }
      $4=opts
      print; next
    }
    {print}
  ' "$fstab" > "${fstab}.tmp"

  mv "${fstab}.tmp" "$fstab"
}

ensure_fstab_swapfile() {
  local path="$1"
  local pri="$2"
  local fstab="/etc/fstab"
  backup_file "$fstab"

  awk -v p="$path" '
    BEGIN{OFS="\t"}
    /^[[:space:]]*#/ {print; next}
    $1==p && $3=="swap" {next}
    {print}
  ' "$fstab" > "${fstab}.tmp"

  echo -e "${path}\tnone\tswap\tsw,pri=${pri}\t0\t0" >> "${fstab}.tmp"
  mv "${fstab}.tmp" "$fstab"
}

create_swapfile() {
  local path="$1"
  local size="$2"

  if [[ -e "$path" ]]; then
    if file -b "$path" 2>/dev/null | grep -qi 'swap file'; then
      echo "ℹ️ 已存在 swapfile: $path（将直接复用）"
      return 0
    fi
    echo "❌ 路径已存在但不是 swapfile: $path"
    echo "   为安全起见，不会覆盖。请换个路径，或手动处理后重试。"
    exit 1
  fi

  echo "🧱 创建 swapfile: $path (大小: $size)"
  if command -v fallocate >/dev/null 2>&1; then
    fallocate -l "$size" "$path"
  else
    echo "⚠️ 系统无 fallocate，建议你用形如 2048M/2G 的大小。"
    dd if=/dev/zero of="$path" bs=1M count=0 seek="$size" status=none
  fi

  chmod 600 "$path"
  mkswap "$path" >/dev/null
}

enable_swap_target() {
  local target="$1"
  local pri="$2"
  if swapon --noheadings --raw --output=NAME 2>/dev/null | grep -qx "$target"; then
    swapoff "$target"
  fi
  swapon -p "$pri" "$target"
}

# sysctl 写入/更新
write_sysctl_conf() {
  local file="/etc/sysctl.d/99-zram-swap.conf"
  backup_file "$file"
  cat > "$file" <<EOF
# Generated by zram+swap setup script
vm.swappiness = $1
vm.page-cluster = $2
EOF
  sysctl --system >/dev/null || true
  echo "✅ 已写入并尝试应用 sysctl: $file"
}

# =========================
# 额外信息：磁盘类型
# =========================
BASE_DISK="$(root_base_disk)"
DISK_KIND="$(disk_is_rotational "$BASE_DISK")"  # ssd/hdd/unknown

# =========================
# 1) zram 推荐配置
# =========================
if (( RAM_MB <= 2048 )); then
  REC_SIZE_EXPR="ram * 3 / 2"; REC_NUM=3; REC_DEN=2
elif (( RAM_MB <= 4096 )); then
  REC_SIZE_EXPR="ram"; REC_NUM=1; REC_DEN=1
elif (( RAM_MB <= 8192 )); then
  REC_SIZE_EXPR="ram * 3 / 4"; REC_NUM=3; REC_DEN=4
elif (( RAM_MB <= 16384 )); then
  REC_SIZE_EXPR="ram / 2"; REC_NUM=1; REC_DEN=2
else
  REC_SIZE_EXPR="ram / 4"; REC_NUM=1; REC_DEN=4
fi

if (( CORES <= 2 )); then
  REC_ALGO="lz4"
else
  if (( RAM_MB <= 4096 )); then REC_ALGO="lz4"; else REC_ALGO="zstd"; fi
fi

if (( HAS_DISK_SWAP == 1 )); then
  REC_ZRAM_PRIO=200
else
  REC_ZRAM_PRIO=100
fi

REC_ZRAM_MB=$(( RAM_MB * REC_NUM / REC_DEN ))

echo "🧠 物理内存: ${RAM_MB} MB"
echo "🧮 CPU 核心数: ${CORES}"
if [[ -n "$BASE_DISK" ]]; then
  echo "💾 根分区磁盘: ${BASE_DISK}（推断类型: ${DISK_KIND}）"
else
  echo "💾 根分区磁盘: 未能确定（推断类型: unknown）"
fi
echo "💽 磁盘 swap: $([[ $HAS_DISK_SWAP -eq 1 ]] && echo '已存在' || echo '不存在')"
echo
echo "👉 推荐 zram 配置:"
echo "   zram-size: ${REC_SIZE_EXPR} (约 ${REC_ZRAM_MB} MB)"
echo "   compression-algorithm: ${REC_ALGO}"
echo "   swap-priority: ${REC_ZRAM_PRIO}"
echo

read -rp "是否使用推荐 zram 配置? [Y/n] " USE_REC
USE_REC=${USE_REC:-Y}

if [[ "$USE_REC" =~ ^[Yy]$ ]]; then
  ZRAM_SIZE="$REC_SIZE_EXPR"
  COMP_ALGO="$REC_ALGO"
  ZRAM_PRIO="$REC_ZRAM_PRIO"
else
  read -rp "请输入 zram-size (如: ram / 2 或 1024M): " ZRAM_SIZE
  read -rp "请选择压缩算法 (lz4/zstd/lzo): " COMP_ALGO
  read -rp "设置 zram swap 优先级? (默认 ${REC_ZRAM_PRIO}) [${REC_ZRAM_PRIO}]: " ZRAM_PRIO
  ZRAM_PRIO=${ZRAM_PRIO:-$REC_ZRAM_PRIO}
fi

case "$COMP_ALGO" in
  lz4|zstd|lzo) ;;
  *) echo "❌ 不支持的压缩算法: $COMP_ALGO"; exit 1 ;;
esac

# =========================
# 2) 磁盘 swap 推荐配置（含 SSD/HDD 智能）
# =========================
echo
echo "👉 磁盘 swap 配置（swapfile / 现有 swap 分区/文件）"

REC_SWAP_ENABLE="Y"
if (( HAS_DISK_SWAP == 1 )); then
  REC_SWAP_MODE="tune"
else
  REC_SWAP_MODE="create"
fi

# 推荐 swapfile 大小（保守，zram 负责主要压力；磁盘 swap 做兜底）
if (( RAM_MB <= 2048 )); then
  REC_SWAP_SIZE="2G"
elif (( RAM_MB <= 4096 )); then
  REC_SWAP_SIZE="2G"
elif (( RAM_MB <= 8192 )); then
  REC_SWAP_SIZE="4G"
elif (( RAM_MB <= 16384 )); then
  REC_SWAP_SIZE="8G"
else
  REC_SWAP_SIZE="8G"
fi

# 推荐磁盘 swap priority（低于 zram；HDD 更低，SSD 可稍高）
# 仍保证 < zram priority
if [[ "$DISK_KIND" == "hdd" ]]; then
  REC_DISK_PRIO=10
elif [[ "$DISK_KIND" == "ssd" ]]; then
  REC_DISK_PRIO=50
else
  REC_DISK_PRIO=30
fi
if (( REC_DISK_PRIO >= ZRAM_PRIO )); then
  REC_DISK_PRIO=$(( ZRAM_PRIO > 20 ? ZRAM_PRIO - 20 : 10 ))
fi

# 推荐 swapfile 路径：放到 / /var /home 中空间最大的挂载点
BEST_MP="$(best_swap_mountpoint)"
REC_SWAPFILE="${BEST_MP%/}/swapfile"
[[ "$REC_SWAPFILE" == "//swapfile" ]] && REC_SWAPFILE="/swapfile"

# 空间太紧时，把推荐 swapfile 降为 1G（仅 create 推荐时）
ROOT_FREE_MB=$(root_free_mb)
if [[ "$REC_SWAP_MODE" == "create" ]]; then
  need_mb=0
  case "$REC_SWAP_SIZE" in
    *G) need_mb=$(( ${REC_SWAP_SIZE%G} * 1024 ));;
    *M) need_mb=$(( ${REC_SWAP_SIZE%M} ));;
    *) need_mb=0;;
  esac
  if (( need_mb > 0 && ROOT_FREE_MB < need_mb + 512 )); then
    echo "⚠️ 根分区可用空间约 ${ROOT_FREE_MB}MB，偏紧；推荐 swapfile 大小降为 1G"
    REC_SWAP_SIZE="1G"
  fi
fi

echo "👉 推荐 swap 方案:"
if [[ "$REC_SWAP_MODE" == "create" ]]; then
  echo "   模式: 创建 swapfile"
  echo "   路径: ${REC_SWAPFILE}"
  echo "   大小: ${REC_SWAP_SIZE}"
else
  echo "   模式: 调整已有 swap priority（不新建 swapfile）"
fi
echo "   磁盘类型推断: ${DISK_KIND}（HDD 会更低 priority 以减少写盘）"
echo "   磁盘 swap priority: ${REC_DISK_PRIO}"
echo

read -rp "是否配置磁盘 swap? [Y/n] " DO_SWAP
DO_SWAP=${DO_SWAP:-Y}

SWAP_ACTION="skip"
SWAP_MODE="$REC_SWAP_MODE"
SWAPFILE_PATH="$REC_SWAPFILE"
SWAPFILE_SIZE="$REC_SWAP_SIZE"
DISK_SWAP_PRIO="$REC_DISK_PRIO"

if [[ "$DO_SWAP" =~ ^[Yy]$ ]]; then
  read -rp "是否使用推荐 swap 方案? [Y/n] " USE_SWAP_REC
  USE_SWAP_REC=${USE_SWAP_REC:-Y}

  if [[ "$USE_SWAP_REC" =~ ^[Yy]$ ]]; then
    SWAP_ACTION="apply"
  else
        echo "自定义 swap 方案："
    echo "  1) create  - 创建/启用 swapfile"
    echo "  2) tune    - 仅调整已有 swap priority（不新建）"
    echo "  3) off     - 关闭所有磁盘 swap（不建议，谨慎使用）"
    read -rp "请选择模式 (1/2/3 或 create/tune/off) [${REC_SWAP_MODE}]: " SWAP_MODE
    SWAP_MODE=${SWAP_MODE:-$REC_SWAP_MODE}

    # 兼容数字输入
    case "$SWAP_MODE" in
      1|create) SWAP_MODE="create" ;;
      2|tune)   SWAP_MODE="tune" ;;
      3|off)    SWAP_MODE="off" ;;
      *)
        echo "❌ 无效选择: $SWAP_MODE（请输入 1/2/3 或 create/tune/off）"
        exit 1
        ;;
    esac

    read -rp "磁盘 swap priority (建议低于 zram) [${REC_DISK_PRIO}]: " DISK_SWAP_PRIO
    DISK_SWAP_PRIO=${DISK_SWAP_PRIO:-$REC_DISK_PRIO}

    # 只要选择 create，就一定询问路径和大小（回车用默认）
    if [[ "$SWAP_MODE" == "create" ]]; then
      read -rp "swapfile 路径 [${REC_SWAPFILE}]: " SWAPFILE_PATH
      SWAPFILE_PATH=${SWAPFILE_PATH:-$REC_SWAPFILE}

      read -rp "swapfile 大小 (如 1G/2G/4096M) [${REC_SWAP_SIZE}]: " SWAPFILE_SIZE
      SWAPFILE_SIZE=${SWAPFILE_SIZE:-$REC_SWAP_SIZE}
    fi

    SWAP_ACTION="apply"
  fi
fi

# =========================
# 3) sysctl 调优（推荐/自定义，可选）
# =========================
echo
echo "👉 sysctl 调优（可选，用于配合 zram+swap）"
# 推荐值：zram 场景下 swappiness 通常提高；page-cluster 设 0 减少 swap readahead（对 zram/SSD 更友好）
REC_SWAPPINESS=180
REC_PAGE_CLUSTER=0

echo "👉 推荐 sysctl:"
echo "   vm.swappiness = ${REC_SWAPPINESS}"
echo "   vm.page-cluster = ${REC_PAGE_CLUSTER}"
echo

read -rp "是否应用 sysctl 推荐/自定义配置? [y/N] " DO_SYSCTL
DO_SYSCTL=${DO_SYSCTL:-N}

SYSCTL_ACTION="skip"
SYS_SWAPPINESS="$REC_SWAPPINESS"
SYS_PAGE_CLUSTER="$REC_PAGE_CLUSTER"

if [[ "$DO_SYSCTL" =~ ^[Yy]$ ]]; then
  read -rp "是否使用推荐 sysctl 配置? [Y/n] " USE_SYSCTL_REC
  USE_SYSCTL_REC=${USE_SYSCTL_REC:-Y}
  if [[ "$USE_SYSCTL_REC" =~ ^[Yy]$ ]]; then
    SYSCTL_ACTION="apply"
  else
    read -rp "vm.swappiness (0-200) [${REC_SWAPPINESS}]: " SYS_SWAPPINESS
    SYS_SWAPPINESS=${SYS_SWAPPINESS:-$REC_SWAPPINESS}
    read -rp "vm.page-cluster (0-3 常用) [${REC_PAGE_CLUSTER}]: " SYS_PAGE_CLUSTER
    SYS_PAGE_CLUSTER=${SYS_PAGE_CLUSTER:-$REC_PAGE_CLUSTER}
    SYSCTL_ACTION="apply"
  fi
fi

# =========================
# 最终确认
# =========================
echo
echo "📄 最终配置:"
echo "----- zram -----"
cat <<EOF
[zram0]
zram-size = $ZRAM_SIZE
compression-algorithm = $COMP_ALGO
swap-priority = $ZRAM_PRIO
EOF

echo
echo "----- disk swap -----"
if [[ "$SWAP_ACTION" == "skip" ]]; then
  echo "不配置磁盘 swap"
else
  echo "模式: $SWAP_MODE"
  echo "磁盘 swap priority: $DISK_SWAP_PRIO"
  if [[ "$SWAP_MODE" == "create" ]]; then
    echo "swapfile: $SWAPFILE_PATH"
    echo "swapfile 大小: $SWAPFILE_SIZE"
  fi
fi

echo
echo "----- sysctl -----"
if [[ "$SYSCTL_ACTION" == "skip" ]]; then
  echo "不修改 sysctl"
else
  echo "vm.swappiness = $SYS_SWAPPINESS"
  echo "vm.page-cluster = $SYS_PAGE_CLUSTER"
fi

echo
read -rp "确认应用以上配置? [Y/n] " CONFIRM
CONFIRM=${CONFIRM:-Y}
[[ "$CONFIRM" =~ ^[Yy]$ ]] || exit 0

# =========================
# 应用 zram 配置
# =========================
echo "📦 安装 systemd-zram-generator..."
apt update
apt install -y systemd-zram-generator

CONF_FILE="/etc/systemd/zram-generator.conf"
backup_file "$CONF_FILE"
echo "✍️ 写入配置: $CONF_FILE"
cat > "$CONF_FILE" <<EOF
[zram0]
zram-size = $ZRAM_SIZE
compression-algorithm = $COMP_ALGO
swap-priority = $ZRAM_PRIO
EOF

echo "🔄 应用 zram 配置..."
systemctl daemon-reload
systemctl restart systemd-zram-setup@zram0.service 2>/dev/null || true
systemctl start systemd-zram-setup@zram0.service 2>/dev/null || true

# =========================
# 应用磁盘 swap 配置
# =========================
if [[ "$SWAP_ACTION" == "apply" ]]; then
  case "$SWAP_MODE" in
    create)
      create_swapfile "$SWAPFILE_PATH" "$SWAPFILE_SIZE"
      ensure_fstab_swapfile "$SWAPFILE_PATH" "$DISK_SWAP_PRIO"
      enable_swap_target "$SWAPFILE_PATH" "$DISK_SWAP_PRIO"
      echo "✅ swapfile 已创建并启用: $SWAPFILE_PATH"
      ;;

    tune)
      if (( HAS_DISK_SWAP == 0 )); then
        echo "⚠️ 未检测到磁盘 swap，tune 模式无事可做。你可以改用 create 模式创建 swapfile。"
      else
        echo "🔧 调整所有磁盘 swap priority 为: $DISK_SWAP_PRIO（并写入 /etc/fstab 持久化）"
        update_fstab_swap_pri_all "$DISK_SWAP_PRIO"

        while read -r dev; do
          [[ -z "$dev" ]] && continue
          if [[ "$dev" =~ ^/dev/zram[0-9]+$ ]]; then
            continue
          fi
          enable_swap_target "$dev" "$DISK_SWAP_PRIO" || true
        done <<< "$DISK_SWAPS"

        echo "✅ 已尝试应用 priority（如有 systemd/其他机制管理，重启后会更一致）"
      fi
      ;;

    off)
      if (( HAS_DISK_SWAP == 0 )); then
        echo "ℹ️ 没有磁盘 swap，无需关闭。"
      else
        echo "⚠️ 关闭所有磁盘 swap（不会删除文件，但会 swapoff）："
        while read -r dev; do
          [[ -z "$dev" ]] && continue
          if [[ "$dev" =~ ^/dev/zram[0-9]+$ ]]; then
            continue
          fi
          swapoff "$dev" || true
        done <<< "$DISK_SWAPS"
        echo "✅ 已关闭磁盘 swap（fstab 未自动清理，如需持久化关闭请手动处理 /etc/fstab）"
      fi
      ;;

    *)
      echo "❌ 未知 swap 模式: $SWAP_MODE"
      exit 1
      ;;
  esac
fi

# =========================
# sysctl 应用
# =========================
if [[ "$SYSCTL_ACTION" == "apply" ]]; then
  # 简单范围校验（防止明显离谱）
  if ! [[ "$SYS_SWAPPINESS" =~ ^[0-9]+$ ]] || (( SYS_SWAPPINESS < 0 || SYS_SWAPPINESS > 200 )); then
    echo "❌ vm.swappiness 非法: $SYS_SWAPPINESS（应为 0-200）"
    exit 1
  fi
  if ! [[ "$SYS_PAGE_CLUSTER" =~ ^[0-9]+$ ]] || (( SYS_PAGE_CLUSTER < 0 || SYS_PAGE_CLUSTER > 9 )); then
    echo "❌ vm.page-cluster 非法: $SYS_PAGE_CLUSTER"
    exit 1
  fi
  write_sysctl_conf "$SYS_SWAPPINESS" "$SYS_PAGE_CLUSTER"
fi

# =========================
# 显示结果
# =========================
echo
echo "✅ 当前 swap 状态："
swapon --show || true
echo
echo "✅ 当前 zram 状态："
zramctl || true
echo
echo "🎉 完成！"